// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using footic.EData;

#nullable disable

namespace footic.Migrations
{
    [DbContext(typeof(PlSimulationDbContext))]
    [Migration("20260421171128_AddMatchTimeAndCleanup")]
    partial class AddMatchTimeAndCleanup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("footic.Models.League", b =>
                {
                    b.Property<int>("LeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LeagueID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeagueId"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Lname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LName");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Winner")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LeagueId");

                    b.HasIndex(new[] { "Lname" }, "UQ_League_Name")
                        .IsUnique();

                    b.ToTable("League", (string)null);
                });

            modelBuilder.Entity("footic.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MatchID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatchId"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<byte>("AwayTeamScore")
                        .HasColumnType("tinyint");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<byte>("HomeTeamScore")
                        .HasColumnType("tinyint");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int")
                        .HasColumnName("LeagueID");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime");

                    b.Property<TimeOnly>("MatchTime")
                        .HasColumnType("time");

                    b.Property<int?>("StadiumId")
                        .HasColumnType("int")
                        .HasColumnName("StadiumID");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.HasKey("MatchId")
                        .HasName("PK_Match");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("StadiumId");

                    b.ToTable("Match_", (string)null);
                });

            modelBuilder.Entity("footic.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PlayerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndContract")
                        .HasColumnType("date");

                    b.Property<int>("Fit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<DateOnly>("Joined")
                        .HasColumnType("date");

                    b.Property<decimal?>("MarketValue")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pimage")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("PImage")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Pname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PName");

                    b.Property<int>("Pnumber")
                        .HasColumnType("int")
                        .HasColumnName("PNumber");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Poweer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50);

                    b.Property<string>("StrongFoot")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TeamID");

                    b.HasKey("PlayerId");

                    b.HasIndex(new[] { "TeamId" }, "IX_Player_TeamID");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("footic.Models.PlayerStat", b =>
                {
                    b.Property<int>("PlayerStatsId")
                        .HasColumnType("int")
                        .HasColumnName("PlayerStatsID");

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("RedCards")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("Weight_");

                    b.Property<int>("YellowCards")
                        .HasColumnType("int");

                    b.HasKey("PlayerStatsId");

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("footic.Models.Stadium", b =>
                {
                    b.Property<int>("StadiumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StadiumID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StadiumId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Logo_url");

                    b.Property<string>("Slocation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SLocation");

                    b.Property<string>("Sname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SName");

                    b.HasKey("StadiumId");

                    b.HasIndex(new[] { "Sname" }, "UQ_Stadium_Name")
                        .IsUnique();

                    b.ToTable("Stadium", (string)null);
                });

            modelBuilder.Entity("footic.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TeamID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("Coach")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("int")
                        .HasColumnName("LeagueID");

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("StadiumId")
                        .HasColumnType("int")
                        .HasColumnName("StadiumID");

                    b.Property<string>("Tname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TName");

                    b.HasKey("TeamId");

                    b.HasIndex(new[] { "LeagueId" }, "IX_Team_LeagueID");

                    b.HasIndex(new[] { "StadiumId" }, "IX_Team_StadiumID");

                    b.HasIndex(new[] { "Tname" }, "UQ_Team_Name")
                        .IsUnique();

                    b.ToTable("Team", (string)null);
                });

            modelBuilder.Entity("footic.Models.TeamStat", b =>
                {
                    b.Property<int>("TeamStatsId")
                        .HasColumnType("int")
                        .HasColumnName("TeamStatsID");

                    b.Property<int>("DrawNumber")
                        .HasColumnType("int");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("int");

                    b.Property<int>("LoseNumber")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("PreviousPosition")
                        .HasColumnType("int");

                    b.Property<int>("WinsNumber")
                        .HasColumnType("int");

                    b.HasKey("TeamStatsId");

                    b.ToTable("TeamStats");
                });

            modelBuilder.Entity("footic.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("TeamID");

                    b.Property<string>("Upassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("UPassword");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("fan");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "TeamId" }, "IX_Users_TeamID");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "UserName" }, "UQ_Users_UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("footic.Models.Match", b =>
                {
                    b.HasOne("footic.Models.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Match_AwayTeam");

                    b.HasOne("footic.Models.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Match_HomeTeam");

                    b.HasOne("footic.Models.League", "League")
                        .WithMany("Matches")
                        .HasForeignKey("LeagueId")
                        .IsRequired()
                        .HasConstraintName("FK_Match_League");

                    b.HasOne("footic.Models.Stadium", "Stadium")
                        .WithMany("Matches")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Match_Stadium");

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("footic.Models.Player", b =>
                {
                    b.HasOne("footic.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK_Player_Team");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("footic.Models.PlayerStat", b =>
                {
                    b.HasOne("footic.Models.Player", "PlayerStats")
                        .WithOne("PlayerStat")
                        .HasForeignKey("footic.Models.PlayerStat", "PlayerStatsId")
                        .IsRequired()
                        .HasConstraintName("FK_PlayerStats_Player");

                    b.Navigation("PlayerStats");
                });

            modelBuilder.Entity("footic.Models.Team", b =>
                {
                    b.HasOne("footic.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .HasConstraintName("FK_Team_League");

                    b.HasOne("footic.Models.Stadium", "Stadium")
                        .WithMany("Teams")
                        .HasForeignKey("StadiumId")
                        .HasConstraintName("FK_Team_Stadium");

                    b.Navigation("League");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("footic.Models.TeamStat", b =>
                {
                    b.HasOne("footic.Models.Team", "TeamStats")
                        .WithOne("TeamStat")
                        .HasForeignKey("footic.Models.TeamStat", "TeamStatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TeamStats_Team");

                    b.Navigation("TeamStats");
                });

            modelBuilder.Entity("footic.Models.User", b =>
                {
                    b.HasOne("footic.Models.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK_Users_Team");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("footic.Models.League", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("footic.Models.Player", b =>
                {
                    b.Navigation("PlayerStat");
                });

            modelBuilder.Entity("footic.Models.Stadium", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("footic.Models.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");

                    b.Navigation("Players");

                    b.Navigation("TeamStat");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
